[package]
name = "advent-of-code-2021"
version = "1.0.0"
edition = "2021"
authors = ["Jacob Prud'homme"]
description = "Solutions for the Advent of Code 2021, in Rust"
repository = "https://github.com/jacobprudhomme/advent-of-code-2020"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day1-part1"
path = "src/day1/part1.rs"
